
name: yamory

on:
  push:
    branches:
      - master
      - yamory-*
jobs:
  build:
    name: Node.js ubuntu-latest 16.x
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: yarn
    - name: download and validate Yamory script
      env:
        # https://cli.yamory.io/yamory-app-library-scan-scripts/yamory-yarn-sha512sum.txt
        YAMORY_YARN_SCRIPT_SHA512: "eb87a80a49f3127f9b048853b043b9f8484b33f2647223ab271f483f5e5297ec528e545dd98d9ca97b09971c7150fcfe262d7b08d65b2ad932d4cbde7679bcbd"
      working-directory: /tmp
      run: |
        curl -sSf -L -o ./yamory-yarn.sh \
        https://localscanner.yamory.io/script/yarn
        echo "${YAMORY_YARN_SCRIPT_SHA512} yamory-yarn.sh" | sha512sum --check -
        chmod +x ./yamory-yarn.sh
    - name: run Yamory
      run: |
        ls -d packages/*/ | xargs -I {} /tmp/yamory-yarn.sh --manifest {}/package.json
        ls -d examples/*/ | xargs -I {} /tmp/yamory-yarn.sh --manifest {}/package.json
      env:
        CI: true
        PROJECT_GROUP_KEY: js-sdk
        YAMORY_API_KEY: ${{ secrets.YAMORY_API_KEY }}
